# Generated by Django 3.0.4 on 2020-06-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-modify_dt',), 'verbose_name': 'board', 'verbose_name_plural': 'boards'},
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='board_boards',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
